version: 2

# {{{ Shared configuration
shared-config:
  images:
    circleci-openjdk-custom: &circleci-openjdk-custom ean-docker-virtual.jfrog.io/elementanalytics/circleci-openjdk-custom:2.0.2

  artifactory-auth: &artifactoryAuth
    username: $ARTIFACTORY_PUBLISH_USER
    password: $ARTIFACTORY_PUBLISH_TOKEN

  caches:
    # Use the digits to bust the cache if needed.
    sbt-build-cache:  &sbt-build-cache  sbt-cache-1-{{ checksum "build.sbt" }}
    sbt-plugin-cache: &sbt-plugin-cache sbt-coverage-cache-1-{{ checksum "project/plugins.sbt" }}
# }}}

jobs:
  build:
    working_directory: ~/keycloak4s
    docker:
      - image: *circleci-openjdk-custom
        auth: *artifactoryAuth
    environment:
      - SCALA_VERSION: 2.12.12
      - SBT_VERSION: 1.4.2
    steps:
      - checkout
      - restore_cache:
          key: *sbt-build-cache
      - run:
          name: credentials
          command: |
            mkdir -p ~/.sbt || true
            deployment/credentials
      - run:
          name: compile
          command:
            sbt -mem 2048 clean test:compile package
      - save_cache:
          key: *sbt-build-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.coursier"
            - "~/.cache/coursier"
            - "~/.m2"
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          # This is a directory on the container which is taken to be the root
          # directory of the workspace.
          root: ~/keycloak4s
          # Must be relative path from root
          paths:
            - target
            - keycloak4s-core/target
            - keycloak4s-admin/target
            - keycloak4s-admin-monix/target
            - keycloak4s-auth/target
            - keycloak4s-playground/target
  test:
    working_directory: ~/keycloak4s
    docker:
      - image: *circleci-openjdk-custom
        auth: *artifactoryAuth
    steps:
      - checkout
      - attach_workspace:
          at: ~/keycloak4s
      - restore_cache:
          key: *sbt-plugin-cache
      - run: deployment/credentials
      - run: sbt -mem 2048 coverage test coverageReport coverageAggregate
      - save_cache:
          key: *sbt-plugin-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.coursier"
            - "~/.cache/coursier"
            - "~/.m2"
  license:
    working_directory: ~/keycloak4s
    docker:
      - image: *circleci-openjdk-custom
        auth: *artifactoryAuth
    steps:
      - checkout
      - attach_workspace:
          at: ~/keycloak4s
      - restore_cache:
          key: *sbt-plugin-cache
      - run: deployment/credentials
      - run: sbt dumpLicenseReport
      - run: mkdir /tmp/license-report
      - run: mv target/license-reports/root-licenses.html /tmp/license-report/index.html
      - store_artifacts:
          path: /tmp/license-report
  publish:
    working_directory: ~/keycloak4s
    docker:
      - image: *circleci-openjdk-custom
        auth: *artifactoryAuth
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ~/keycloak4s
      - restore_cache:
          key: *sbt-build-cache
      - run: deployment/credentials
      - run: deployment/artifactory

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /^v[0-9].*/
      - test:
          requires:
            - build
          context: org-global
          filters:
            tags:
              only: /^v[0-9].*/
      - license:
          requires:
            - build
          context: org-global
          filters:
            tags:
              only: /^v[0-9].*/
      - publish:
          requires:
            - test
          context: org-global
          filters:
            tags:
              only: /^v[0-9].*/
